# Generated by Django 4.2.4 on 2023-10-11 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_country_user_picture_alter_user_province'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='usertype',
            field=models.CharField(choices=[('client', 'Client'), ('photographer', 'Photographer')], default='client', max_length=20),
        ),
    ]
