# Generated by Django 4.2.4 on 2023-10-12 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_usertype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='picture',
            field=models.ImageField(default='users/defaultprofile.svg', upload_to='users'),
        ),
    ]
