# Generated by Django 4.2.4 on 2023-10-12 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_user_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='picture',
            field=models.ImageField(default='defaultprofile.svg', upload_to='users'),
        ),
    ]
