# Generated by Django 4.2.4 on 2023-10-15 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_user_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='province',
            new_name='provinces',
        ),
    ]
