# Generated by Django 4.2.4 on 2023-10-23 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_user_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='picture',
            field=models.ImageField(blank=True, default='defaultprofile.svg', null=True, upload_to='users'),
        ),
    ]
