# Generated by Django 4.2.4 on 2023-10-29 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_alter_photographer_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='photographer',
            new_name='userPhotographer',
        ),
    ]
