# Generated by Django 4.2.4 on 2023-10-29 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_rename_photographer_userphotographer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='picture',
            field=models.ImageField(default='defaultprofile.svg', null=True, upload_to='users'),
        ),
    ]
